baseURL: https://www.punkt-a.net/
theme: minimal-event-location
title: Punkt A

languageCode: de-de
timeZone: Europe/Berlin
defaultContentLanguage: de
languages:
  de:
    weight: 1
    params:
      defaultSummary: Zusammen, kostenlos und draußen Parkour in Hamburg trainieren.
      announcement: "Hinweis: Wegen Verletzung aktuell Pause bis ca. September 2022."
  en:
    weight: 2
    params:
      defaultSummary: Do Parkour together, free of charge and outdoors in Hamburg.
      announcement: "Notice: Because of injury we're taking a break until approx. September 2022."

params:
  email: punkt-aⒶsystemli.org
  location: Spot
  event: Training
  timezone: Europe/Berlin
  logo:
    path: /images/logo.svg
    line1: Punkt A
    line2: Parkour in Hamburg
  umap: https://umap.openstreetmap.fr/en/map/punkt-a-spots_746905
  footer:
    url: https://creativecommons.org/publicdomain/zero/1.0/
    logos:
      - path: /images/a-circle.svg
        alt: A in a circle
      - path: /images/cc-zero.svg
        alt: CC0 sign
      - path: /images/public-domain.svg
        alt: No copyright/public domain sign

sitemap:
  changefreq: daily
  priority: 0.5

menu:
  main:
    - name: Trainings
      url: events/
      weight: 1
    - name: Spots
      url: locations/
      weight: 2
    - name: About
      url: about/
      weight: 3
    - name: FAQ
      url: faq/
      weight: 4

outputs:
  section:
    - HTML
    - RSS
    - GEOJSON
    - ICS

taxonomies:
  category: categories
  locationtag: locationtags
